docs(api-reference/core): selector translation
docschina/Recoil pull request #65
Opened 2021-05-07 13:19 UTC by KnowsCount

2021-05-07 13:21 UTC, KnowsCount commented on docs/docs/api-reference/core/selector.md
> +选择器还可以具有异步求值函数，并将 `Promise` 返回到输出里。更多信息，请参阅[本指南](/docs/guides/asynchronous-data-queries)
链接之前要空格……

```suggestion
选择器还可以具有异步求值函数，并将 `Promise` 返回到输出里。更多信息，请参阅 [本指南](/docs/guides/asynchronous-data-queries)
```

2021-05-07 16:47 UTC, QC-L commented on docs/docs/api-reference/core/selector.md
> +在 Recoil 里，_selector_ 代表一个函数，或 **派生状态**。你可以把它们看作是类似于一个没有副作用的 "幂等" 或 "纯函数"，对于一组给定的依赖值永远返回相同的值。如果只提供 `get` 方法，则 selector 是只读的，并返回 `RecoilValueReadOnly` 对象。 如果还提供了一个 `set`，它将返回一个可写的 `RecoilState` 对象。
```suggestion
在 Recoil 里，_selector_ 代表一个函数，或 **派生状态**。你可以把它们看作是类似于一个没有副作用的 "幂等" 或 "纯函数"，对于一组给定的依赖值永远返回相同的值。如果只提供 `get` 方法，则 selector 是只读的，并返回 `RecoilValueReadOnly` 对象。如果还提供了一个 `set`，它将返回一个可写的 `RecoilState` 对象。
```

2021-05-07 16:50 UTC, QC-L commented on docs/docs/api-reference/core/selector.md
> +为了知道何时通知订阅该 selector 的组件重新渲染，Recoil 会管理 atom 以及 selector 的状态变化。如果一个 selector 的对象值直接被改变，它可能会绕过这个，以避免通知订阅它的组件。为了帮助检测 bug，Recoil 将在开发模式下冻结 selector 的值对象。
```suggestion
为了知道何时通知订阅该 selector 的组件重新渲染，Recoil 会管理 atom 以及 selector 的状态变化。如果一个 selector 的对象值被直接改变，它可能会绕过管理，以避免通知订阅它的组件。为了帮助检测 bug，Recoil 将在开发模式下 freeze selector 的值对象。
```

2021-05-07 16:51 UTC, QC-L commented on docs/docs/api-reference/core/selector.md
> +为了知道何时通知订阅该 selector 的组件重新渲染，Recoil 会管理 atom 以及 selector 的状态变化。如果一个 selector 的对象值直接被改变，它可能会绕过这个，以避免通知订阅它的组件。为了帮助检测 bug，Recoil 将在开发模式下冻结 selector 的值对象。
应该是 Object.freeze()

2021-05-07 16:54 UTC, QC-L commented on docs/docs/api-reference/core/selector.md
> +只读选择器有一个 `get` 方法，该方法根据依赖关系计算的值。如果这些依赖项中的任何一个被更新，那么选择器将重新计算。依赖关系是根据在评估 selector 时实际使用的 atom 或 selector 动态确定的。根据先前依赖项的值，你可以动态地使用不同的附加依赖项。Recoil 将自动更新当前的数据流图，以便选择器只订阅来自当前依赖关系集的更新。
```suggestion
只读选择器有一个 `get` 方法，该方法会根据依赖关系计算选择器的值。如果这些依赖项中的任何一个被更新，那么选择器将重新计算。依赖关系是根据在评估 selector 时实际使用的 atom 或 selector 动态确定的。根据先前依赖项的值，你可以动态地使用不同的附加依赖项。Recoil 将自动更新当前的数据流图，以便选择器只订阅来自当前依赖关系集的更新。
```

2021-05-07 16:54 UTC, QC-L commented on docs/docs/api-reference/core/selector.md
多加了个空行...和英文保持一致吧，不然很麻烦。可以去给英文提 PR 说他们不规范~

2021-05-07 18:00 UTC, KimYangOfCat reviewed
对部分内容做了意译优化，让句子更加流畅，不一定准确，仅供参考。

2021-05-07 18:00 UTC, KimYangOfCat commented on docs/docs/api-reference/core/selector.md
> +在 Recoil 里，_selector_ 代表一个函数，或 **派生状态**。你可以把它们看作是类似于一个没有副作用的 "幂等" 或 "纯函数"，对于一组给定的依赖值永远返回相同的值。如果只提供 `get` 方法，则 selector 是只读的，并返回 `RecoilValueReadOnly` 对象。 如果还提供了一个 `set`，它将返回一个可写的 `RecoilState` 对象。
```suggestion
在 Recoil 里，_selector_ 代表一个函数，或 **派生状态**。你可以把它们看作是类似于一个没有副作用的 "幂等操作" 或 "纯函数"，对于一组给定的依赖值永远返回相同的值。如果只提供 `get` 方法，则 selector 便是只读的，并且会返回一个 `RecoilValueReadOnly` 对象。 如果还提供了一个 `set` 方法，它的返回值将变为一个可写的 `RecoilState` 对象。
```
做了一点儿意译的美化，让句子更流畅～仅供参考，不一定准确

2021-05-07 18:00 UTC, KimYangOfCat commented on docs/docs/api-reference/core/selector.md
> +为了知道何时通知订阅该 selector 的组件重新渲染，Recoil 会管理 atom 以及 selector 的状态变化。如果一个 selector 的对象值直接被改变，它可能会绕过这个，以避免通知订阅它的组件。为了帮助检测 bug，Recoil 将在开发模式下冻结 selector 的值对象。
```suggestion
为了知道何时通知订阅该 selector 的组件重新渲染，Recoil 会自动管理 atom 以及 selector 的状态变化。如果一个 selector 的对象值直接被改变，它可能会绕过这个，以避免通知订阅它的组件。为了帮助检测 bug，Recoil 将在开发模式下冻结 selector 的值对象。
```
it may bypass this 中这个 this 指的内容是什么呢？翻译时指出来会不会好点？目前这样，读起来有点儿让人看不懂。

2021-05-07 18:00 UTC, KimYangOfCat commented on docs/docs/api-reference/core/selector.md
> +只读选择器有一个 `get` 方法，该方法根据依赖关系计算的值。如果这些依赖项中的任何一个被更新，那么选择器将重新计算。依赖关系是根据在评估 selector 时实际使用的 atom 或 selector 动态确定的。根据先前依赖项的值，你可以动态地使用不同的附加依赖项。Recoil 将自动更新当前的数据流图，以便选择器只订阅来自当前依赖关系集的更新。
```suggestion
只读 selector 有一个 `get` 方法，该方法会根据依赖关系计算 selector 的值。如果这些依赖项中的任何一个更新了，那么 selector 的值也将重新计算。求该 selector 的值时，其依赖关系是基于实际使用的 atoms 或 selectors 动态确定的。根据先前依赖项的值，你可以动态地使用不同的附加依赖项。Recoil 将自动更新当前的数据流图，因此 selector 只需订阅来自当前依赖关系集的更新。
```
selector 的翻译应该保持一致，如果前面没有翻译，后面也不应翻译，在本文档中，selector 是一个特殊的概念，所以不建议直译。

2021-05-07 18:00 UTC, KimYangOfCat commented on docs/docs/api-reference/core/selector.md
> +在这个示例中，`mySelector` 将取决于 `toggleState` 的 atom 以及 `selector` 或 `selectorB`，具体取决于 `toggleState` 的状态。
```suggestion
在这个示例中，`mySelector` 将取决于 `toggleState` 的 atom 以及依赖于 `toggleState` 状态的 `selector` 或 `selectorB`。
```
这个depending on the state of `toggleState` 应该是修饰前面 的 `selectorA` or `selectorB` 吧，as well as 前后应该是两个并列对象吧～ 仅供参考

2021-05-07 18:00 UTC, KimYangOfCat commented on docs/docs/api-reference/core/selector.md
> +一个双向选择器 (bi-directional selector) 接收传入值作为参数，并可以使用该参数沿数据流图向上游传递更改。因为用户可以使用新值设置选择器，同时也可以重置选择器，所以传入的值要么与选择器表示的类型相同，要么是表示重置操作的 `DefaultValue` 对象。
```suggestion
一个双向 (bi-directional) selector 接收传入值作为参数，并可以使用该参数沿数据流图向上游传递更改。因为用户既可以选择使用新值设置 selector，也可以选择重置 selector，所以传入的值要么是与 selector 表示的同类值，要么是表示重置操作的 `DefaultValue` 对象。
```

2021-05-07 18:00 UTC, KimYangOfCat commented on docs/docs/api-reference/core/selector.md
> +这个简单的 selector 将一个 atom 包装起来，以添加一个额外的字段。只是将 set 和 reset 操作传递给上游的 atom。
```suggestion
这个简单的 selector 实质上包装了一个 atom 来添加一个额外的字段。它仅仅只是将 set 和 reset 操作传递给了上游的 atom。
```

2021-05-07 18:00 UTC, KimYangOfCat commented on docs/docs/api-reference/core/selector.md
> +这个 selector 转换了数据，所以需要检查看看传入值是否是一个 `DefaultValue`。
```suggestion
这个 selector 转换了数据，所以需要检查传入值是否是一个 `DefaultValue`。
```

2021-05-07 18:00 UTC, KimYangOfCat commented on docs/docs/api-reference/core/selector.md
> +选择器还可以具有异步求值函数，并将 `Promise` 返回到输出里。更多信息，请参阅 [本指南](/docs/guides/asynchronous-data-queries)
```suggestion
Selectors 还可以具有异步求值函数，并将一个 `Promise` 作为返回值。更多信息，请参阅 [此指南](/docs/guides/asynchronous-data-queries)
```

2021-05-07 18:08 UTC, KimYangOfCat commented
@QC-L  @lvocin  在本文档中 atom 和 selector 两个词明显具有特殊含义，可以说是专用名词。为避免读者因直译的普通含义造成误解，我个人认为有必要确定一个统一的翻译方法，或者直接不翻译，又或者直译加小括号注释，如 选择器(selector)等等。
开启一个 isuue 或者 wiki 来专门收集这类不用翻译的词，以形成词表？

2021-05-08 01:09 UTC, QC-L commented
@KimYangOfCat 可以的，词汇表在 React 中有示例，你可以参考 https://github.com/reactjs/zh-hans.reactjs.org

2021-05-08 02:56 UTC, Ivocin requested changes

2021-05-08 02:56 UTC, Ivocin commented on docs/docs/api-reference/core/selector.md
> +在这个示例中，`mySelector` 将取决于 `toggleState` 的 atom 以及 `selector` 或 `selectorB`，具体取决于 `toggleState` 的状态。
对的，看下面代码是这个意思

2021-05-08 03:13 UTC, KnowsCount commented on docs/docs/api-reference/core/selector.md
> +在这个示例中，`mySelector` 将取决于 `toggleState` 的 atom 以及依赖于 `toggleState` 状态的 `selector` 或 `selectorB`。
```suggestion
只读 selector 有一个 `get` 方法，该方法会根据依赖关系计算 selector 的值。如果这些依赖项中的任何一个更新了，那么 selector 的值也将重新计算。求该 selector 的值时，其依赖关系是基于实际使用的 atoms 或 selectors 动态确定的。根据先前依赖项的值，你可以动态地使用不同的附加依赖项。Recoil 将自动更新当前的数据流图，因此 selector 只需订阅来自当前依赖关系集的更新。
在这个示例中，`mySelector` 将取决于 `toggleState` 的 atom 以及依赖于 `toggleState` 状态的 `selector` 或 `selectorB`。
```

2021-05-08 03:14 UTC, KnowsCount commented on docs/docs/api-reference/core/selector.md
好的，我先按照他原来的弄

2021-05-08 03:15 UTC, KnowsCount commented on docs/docs/api-reference/core/selector.md
> +在 Recoil 里，_selector_ 代表一个函数，或 **派生状态**。你可以把它们看作是类似于一个没有副作用的 "幂等操作" 或 "纯函数"，对于一组给定的依赖值永远返回相同的值。如果只提供 `get` 方法，则 selector 便是只读的，并且会返回一个 `RecoilValueReadOnly` 对象。 如果还提供了一个 `set` 方法，它的返回值将变为一个可写的 `Recoi
```suggestion
在 Recoil 里，_selector_ 代表一个函数，或 **派生状态**。你可以把它们看作是类似于一个没有副作用的 "幂等操作" 或 "纯函数"，对于一组给定的依赖值永远返回相同的值。如果只提供 `get` 方法，则 selector 便是只读的，并且会返回一个 `RecoilValueReadOnly` 对象。如果还提供了一个 `set` 方法，它的返回值将变为一个可写的 `RecoilState` 对象。
```

2021-05-08 03:15 UTC, c-z-chen commented on docs/docs/api-reference/core/selector.md
> +为了知道何时通知订阅该 selector 的组件重新渲染，Recoil 会管理 atom 以及 selector 的状态变化。如果一个 selector 的对象值被直接改变，它可能会绕过管理，以避免通知订阅它的组件。为了帮助检测 bug，Recoil 将在开发模式下 freeze selector 的值对象。
```suggestion
为了知道何时通知订阅该 selector 的组件重新渲染，Recoil 会自动管理 atom 以及 selector 的状态变化。如果一个 selector 的对象值被直接改变，它可能会绕过管理，以避免通知订阅它的组件。为了帮助检测 bug，Recoil 将在开发模式下 freeze selector 的值对象。
```

2021-05-08 03:17 UTC, KnowsCount commented on docs/docs/api-reference/core/selector.md
> +为了知道何时通知订阅该 selector 的组件重新渲染，Recoil 会管理 atom 以及 selector 的状态变化。如果一个 selector 的对象值直接被改变，它可能会绕过这个，以避免通知订阅它的组件。为了帮助检测 bug，Recoil 将在开发模式下冻结 selector 的值对象。
对；
@QC-L 刚刚改过了

2021-05-08 03:18 UTC, KnowsCount reviewed
我把大家的建议 commit 进去了，应该好些了

2021-05-08 03:24 UTC, QC-L commented on docs/docs/api-reference/core/selector.md
```suggestion
```

2021-05-08 03:25 UTC, QC-L approved these changes

2021-05-08 05:47 UTC, Ivocin approved these changes

2021-05-08 05:48 UTC, merged