Basic Tutorial （基础教程）翻译
docschina/Recoil pull request #7
Opened 2020-05-22 23:11 UTC by Sunnysit

翻译Basic Tutorial（基础教程）的3个文件

- 介绍（intro.md）
- atoms.md
- selectors.md

2020-05-23 07:21 UTC, QC-L commented on docs/docs/basic-tutorial/atoms.mdx
> +Atoms 包含我们应用中状态的来源。在我们的待办事项清单（todo-list）中，来源将会是一个对象数组，每个对象代表一个待办事项（todo-item）。
Atoms -> Atom

2020-05-23 07:22 UTC, QC-L commented on docs/docs/basic-tutorial/atoms.mdx
> +我们将列表的 atom 称为`todoListState`，并使用`atom（)`函数创建它：
```suggestion
我们将列表的 atom 称为 `todoListState`，并使用 `atom（)` 函数创建它：
```

2020-05-23 07:24 UTC, QC-L commented on docs/docs/basic-tutorial/atoms.mdx
> +我们为该 atom 设定一个唯一的`键（key）`，并将`默认值`设置为一个空数组。 要读取该 atom 的内容，我们可以在`TodoList`组件中使用`useRecoilValue()` hook：
```suggestion
我们为该 atom 设定一个唯一的 `key`，并将`默认值`设置为一个空数组。 要读取该 atom 的内容，我们可以在 `TodoList` 组件中使用 `useRecoilValue()` hook：
```

2020-05-23 07:25 UTC, QC-L commented on docs/docs/basic-tutorial/atoms.mdx
> +要创建新的待办事项，我们需要访问一个 setter 函数，该函数将更新`todoListState`的内容。 我们可以使用`useSetRecoilState()` hook 在`TodoItemCreator`组件中获取一个 setter 函数：
```suggestion
要创建新的待办事项，我们需要访问一个 setter 函数，该函数将更新 `todoListState` 的内容。我们可以使用 `useSetRecoilState()` hook 在 `TodoItemCreator` 组件中获取一个 setter 函数：
```

2020-05-23 07:25 UTC, QC-L commented on docs/docs/basic-tutorial/atoms.mdx
> +`TodoItem`组件将显示待办事项的值，同时允许你更改其文本和删除它。 我们使用`useRecoilState()`读取`todoListState`并获取一个 setter 函数，该函数用于更新项目文本，将其标记为完成并删除它：
```suggestion
`TodoItem` 组件将显示待办事项的值，同时允许你更改其文本和删除它。 我们使用 `useRecoilState()` 读取 `todoListState` 并获取一个 setter 函数，该函数用于更新项目文本，将其标记为完成并删除它：
```

2020-05-23 07:27 UTC, QC-L commented on docs/docs/basic-tutorial/atoms.mdx
> +有了它，我们就有了功能齐全的待办事项清单！ 在下一节中，我们将看到如何使用 selectors 让待办事项清单更进一步。
```suggestion
有了它，我们就有了函数式的 TodoList！在下一节中，我们将看到如何使用 selectors 让 TodoList 更进一步。
```

2020-05-23 07:29 UTC, QC-L commented
Todo List 要不不翻译了吧？翻译成待办事件清单挺难受的...

2020-05-23 23:35 UTC, Sunnysit commented
> @Sunnysit Todo List 要不不翻译了吧？翻译成待办事件清单挺难受的...

@QC-L OK,哈哈

2020-05-24 01:13 UTC, QC-L commented on docs/docs/basic-tutorial/atoms.mdx
> +Atoms 包含我们应用中状态的来源。在我们的待办事项清单（todo-list）中，来源将会是一个对象数组，每个对象代表一个待办事项（todo-item）。
英译中之后，英文就没有复数了~

2020-05-24 01:19 UTC, QC-L commented
通篇改下待办事件清单吧？

2020-05-24 13:13 UTC, QC-L commented on docs/docs/basic-tutorial/selectors.md
> +- 待办事项总数
```suggestion
- Todo Item 总数
```

2020-05-24 13:14 UTC, QC-L commented on docs/docs/basic-tutorial/selectors.md
> +要显示过滤后的待办事项列表只需要在`TodoList`组件中更改一行代码就能实现：
```suggestion
要显示过滤后的 TodoList 只需要在 `TodoList` 组件中更改一行代码就能实现：
```

2020-05-25 01:09 UTC, QC-L commented on docs/docs/basic-tutorial/intro.md
> +title: 介绍
```suggestion
title: 简介
```

2020-05-25 01:09 UTC, QC-L approved these changes

2020-05-25 02:12 UTC, yuqingc requested changes

2020-05-25 02:12 UTC, yuqingc commented on docs/docs/basic-tutorial/atoms.mdx
> +我们将列表的 atom 称为`todoListState`，并使用`atom（)`函数创建它：
@Sunnysit 这个空格问题可以统一改下

2020-05-25 02:12 UTC, yuqingc commented on docs/docs/basic-tutorial/intro.md
> +本章节假定你已经安装了 Recoil 和 React。 有关如何从头开始使用 Recoil 和 React 的信息，请参阅“[快速上手](/docs/introduction/getting-started)”页面。 假定以下各章节中的组件在组件树中已具有`<RecoilRoot />`。
快速上手不用引号

2020-05-25 02:12 UTC, yuqingc commented on docs/docs/basic-tutorial/atoms.mdx
> +我们将列表的 atom 称为 `todoListState`，并使用 `atom（)` 函数创建它：
```suggestion
我们将列表的 atom 称为 `todoListState`，并使用 `atom()` 函数创建它：
```

2020-05-26 04:33 UTC, QC-L approved these changes

2020-05-26 04:48 UTC, merged